name: Expander test

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  expander:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Run test_expander.py
        run: pytest
