name: Unittest(MSVC)

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  gtest-msvc:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-2022
            msvc: "Visual Studio 17 2022"
          - os: windows-2019
            msvc: "Visual Studio 16 2019"

    steps:
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.1
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: run unittest
        run: |
          cd test/unittest &&
          mkdir build &&
          cd build &&
          cmake .. -G "${{ matrix.msvc }}" -A x64 -Dgtest_force_shared_crt=TRUE &&
          msbuild ACLibrary.sln &&
          ctest -C Debug -V
